### PR TITLE
Add `sc.zeros_like` and `sc.ones_like` functions

### PR DESCRIPTION
**Pull request by nvaytet**

### CODE REVIEW

**Review by SimonHeybrock — COMMENTED** [review]
No tests? Also `empty_like` could be useful?

**Comment by nvaytet** [comment]
> No tests? Also `empty_like` could be useful?

Yes, was not ready, forgot to mark as draft

**Review by SimonHeybrock — APPROVED** [review]

**Review by jl-wynen — COMMENTED** [review]
it would be useful if the user could overwrite individual arguments. I often use `np.zeros_like` to get an array with the same dtype but different shape as something else. Since in scipp, we have more parameters, this might be even more useful to, e.g., change only the unit.

**Comment by SimonHeybrock** [comment]
> it would be useful if the user could overwrite individual arguments. I often use `np.zeros_like` to get an array with the same dtype but different shape as something else. Since in scipp, we have more parameters, this might be even more useful to, e.g., change only the unit.

Agree, but we can add that later.

**Pull request merged**
