### PR TITLE
Switch from PNG logo to SVG logo

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Not sure why we did not do this originally...

### CODE REVIEW

**Review by nvaytet — APPROVED** [review]
Are we not removing the old png files to preserve the history?

**Review by jl-wynen — COMMENTED** [review]
The page seems to be too small:
Screenshot_20220823_103906

Also, did you check if the logo is rendered properly? It might be an inkscape-svg and not standard svg. So browsers might struggle.

**Comment by jl-wynen** [comment]
And a tiny, nit picky detail, the 'i' is a little bit too far up.

**Comment by SimonHeybrock** [comment]
The page size looks correct when I open it. It built the docs locally and it looked correct.

**Comment by SimonHeybrock** [comment]
> And a tiny, nit picky detail, the 'i' is a little bit too far up.

You got the wrong font.

**Comment by jl-wynen** [comment]
> You got the wrong font.

Can you export to a path? This could cause problems in the browser as well

**Comment by nvaytet** [comment]
I looked at the docs that github actions made and it looks fine
Screenshot at 2022-08-23 10-43-44

**Comment by jl-wynen** [comment]
Not on my machine
Screenshot_20220823_104512

**Comment by SimonHeybrock** [comment]
> > You got the wrong font.
> 
> Can you export to a path? This could cause problems in the browser as well

Then we need to have two files again. Can we postpone that until we encounter issues? The font is really common.

**Comment by SimonHeybrock** [comment]
> Not on my machine Screenshot_20220823_104512

Hmmm :(

**Pull request merged**
