### PR TITLE
Use a second point cloud for cut surfaces in 3d plots

### PR DESCRIPTION
**Pull request by nvaytet**
This is an attempt to alleviate some issues when rendering semi-transparent points in the 3d plots.
This most commonly arises when we use the cut-surface buttons.

In `threejs`, when objects are rendered, a `depthTest` is performed by default on the object, and any object that would be hidden by another along the camera line of sign is not drawn in the scene, to save on computational cost.
However, this depth test does not consider transparency.
So we can end up with some very transparent pixels in the foreground causing opaque pixels in the background (that should be visible to the eye through the transparent pixels) to not be drawn.

To mitigate this problem, we simply turned `depthTest` off whenever a cut slice was made.
However, this has its own disadvantages. The points are now drawn in the order they are stored in the array, and this means that depending on the camera angle (when we rotate around the scene), we can see some point that should in principle be at the back of the scene coming to the front, because they have been drawn after the points in the foreground.

In this PR, we take a new approach whereby instead of having different opacities for different points in the cloud, we create a new point cloud for the cut slice, make that opaque, and set the opacity to something low for the original point cloud. This seems to work much better with regards to the issue above. This is also nice because we no longer have to write our custom shader that handles rgba colors, we just set the opacity for the entire point cloud material with a single float value.

Example:
```Py
import scipp as sc
import numpy as np
x = np.arange(50.) / 50.
x, y, z = np.meshgrid(x, x, x)
# Purposefully split the points in two halves to reveal the split at the center of the x axis
positions1 = np.array([x.flatten(), y.flatten(), z.flatten()]).astype('float32').T
positions2 = np.array([-x.flatten(), y.flatten(), z.flatten()]).astype('float32').T
positions = np.concatenate([positions1, positions2])
da = sc.DataArray(
    data=sc.array(dims=['xyz'], values=np.sin(positions[:, 1])),
    coords={
        'xyz':sc.vectors(dims=['xyz'], unit='m', values=positions),
})
da.plot(projection='3d', positions='xyz')
```

Before: (notice the rift in the middle because of how we are storing the points: first half positive `x`, second half negative `x`)
Screenshot at 2021-11-15 21-16-35

After:
Screenshot at 2021-11-15 21-17-07

**Cons of this approach**
When we want to move a cut slice with the cut slice position slider, we have to remove the point cloud from the scene, and add a new one in after that. This is because the new slice most often contains a different number of points, and in `pythreejs` we cannot change the number of points in an existing point cloud.
This causes the cut slice to flicker as we are moving it along.
As a workaround, we have disabled `continuous_update` on the cut slice position slider (and removed the checkbox that toggles `continuous_update`), so that the flickering is no longer visible.
I think that continuous updates were making things quite slow anyway when a large number of pixes was present, and is it probably a better default.

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
I see this "plane" in the middle, is this expected: 
image

**Comment by SimonHeybrock** [comment]
Here is another example (increased to 2 million points): 
image

That aside, I think performance is quite good (more than acceptable)... and it is actually *better* than before (especially with many pixels and a "thin" slice, which is the most useful application). 👍

**Comment by nvaytet** [comment]
Yes, that plane is basically what we were seeing before, but it should be less visible now.
I can't seem to be able to get rid of it completely.... :-(

**Comment by nvaytet** [comment]
Should we also remove the continuous update on the `tof` slider?

**Comment by SimonHeybrock** [comment]
> Should we also remove the continuous update on the `tof` slider?

You mean only for the 3d scatter plot, or in general?

**Comment by nvaytet** [comment]
> > Should we also remove the continuous update on the `tof` slider?
> 
> You mean only for the 3d scatter plot, or in general?

I think we'll leave it for now, and re-visit once we have a more extended discussion about the plotting and the resampling mechanism.

**Review by SimonHeybrock — COMMENTED** [review]
Can you add something to the release notes?

**Review by SimonHeybrock — APPROVED** [review]

**Pull request merged**
