### PR TITLE
Configure files for scipp functions using cmake

### PR DESCRIPTION
**Pull request by SimonHeybrock**
It has been suggested from various sides to use a macro or other helpers to avoid repeated boilerplate code when defining simple functions. However, this would still require touching many files (variable header and source, dataset header and source, Python bindings). Here, I am introducing a cmake-based solution. A couple examples have been added, this can be extended.

- It is now much simpler to add new functions.
- If we decide to, e.g., support `out` arguments for `DataArray` functions, we just have to change a single files.

Questions:
- What should we do with tests of these functions in `variable/`, `dataset/`, and `python/`? I think they should be removed. We should just have a single test that tests the base files used for generation (in addition to the tests of the individual kernels in `core/`).

Future work:
- Can maybe partially be extented to also generate the kernels for common cases.
- Could also generate the Python wrappers. Help texts are often similar. On the other hand, this would maybe go too far.
- Add templates for binary functions, and use mechanism for more cases.

### CODE REVIEW

**Comment by jl-wynen** [comment]
Interesting idea. I am a bit concerned about readability though. With this, the generated functions are almost invisible in the source code and one has to look at the separate CMake files. This also hurts tooling because most programs will not be able to find the generated functions, I think.

Does this have advantages over preprocessor macros (apart from avoiding the preprocessor)? The only one I can see is that it handles both Variable and Dataset in one go whereas we would have to handle both separately with macros.

We could also use a dedicated code generator. But this would be one more dependency...

Can this handle cases like `isnan` where the input and output have different types?

**Comment by SimonHeybrock** [comment]
> Interesting idea. I am a bit concerned about readability though. With this, the generated functions are almost invisible in the source code and one has to look at the separate CMake files.

Not sure why we would need to read those files frequently? Maybe the documentation is a better reference for functions that are available? We could maybe auto-generate the function list in the docs as well.

> This also hurts tooling because most programs will not be able to find the generated functions, I think.

They should, because the generated files are included and listed in the `SRC_FILES` and `INC_FILES` in the `CMakeLists.txt`.

> Does this have advantages over preprocessor macros (apart from avoiding the preprocessor)? The only one I can see is that it handles both Variable and Dataset in one go whereas we would have to handle both separately with macros.

- As far as I can tell you would have to put these macros in about 5 places (potentially more in the future). With this you touch only a single file, not 5 (which may inrease to 7 or 8 in the future, if what I mention in the PR is implemented as well).
- Since you touch more places, you may have a bigger risk for bugs.

> We could also use a dedicated code generator. But this would be one more dependency...

What is wrong with cmake?

> Can this handle cases like `isnan` where the input and output have different types?

It can handle anything you like, if you make a corresponding template. Of course that is only worth it

**Comment by SimonHeybrock** [comment]
> Interesting idea. I am a bit concerned about readability though. With this, the generated functions are almost invisible in the source code and one has to look at the separate CMake files.

Why would you have to read it, if it is auto-generated? We should rather complain about the current case where there *is* code to read. Even in the macro solution there is code to read. In my opinion no-existant code is easier to read than any other code.

**Comment by SimonHeybrock** [comment]
I added generation of binary function files. Comparison functions serve as an example.

**Comment by SimonHeybrock** [comment]
> I added generation of binary function files. Comparison functions serve as an example.

As aside-effect, this adds these operators for `DataArray`. These have previously been missing.

**Review by matthew-d-jones — APPROVED** [review]
I can't spot any problems in implementation and I agree with the your suggestion for what to do about testing.

**Pull request merged**
