### PR TITLE
Optimize sizes and shape of data group

### PR DESCRIPTION
**Pull request by jl-wynen**
Alternative to #2996

Sorry, Simon, I didn't mean to rain on your parade but I saw an option to optimise further by doing only a single pass over the data group's items. This code isn't as pretty any more but it avoid overhead from extra function calls (`dim_size`).

Timings:
```python
# old -> #2996 -> this PR in ms
dg = sc.DataGroup({f'{i}':sc.scalar(i) for i in range(1000)})  # 1.3 -> 2.5 -> 1.3
dg = sc.DataGroup({f'{i}':sc.array(dims=[f'{i//100}'], values=[i]) for i in range(1000)}) # 15.6 -> 3.0 -> 1.6
dg = sc.DataGroup()  # 30 -> 6 -> 3
for i in range(1000):
    dg[f'{i}'] = sc.array(dims=[f'{i//100}'], values=[i])
    dg[f'{i}x'] = sc.scalar(i)
```

### CODE REVIEW

**Review by SimonHeybrock — COMMENTED** [review]
Looks good apart from the possible pessimization in `dg.dims` that we discussed earlier.

**Comment by jl-wynen** [comment]
I see about 10% performance degradation in `dims`. Is this worth keeping the old implementation around?

**Comment by SimonHeybrock** [comment]
The old `dims` was roughly constant in `ndim`, whereas `shape` scaled somewhat linearly with it. How about the new `dims`?

**Comment by jl-wynen** [comment]
I get as a function of `ndim`:
```
(new)  1.35, 1.5, 1.69, 1.97, 2.19, 2.35 ms
(old)  1.32, 1.32, 1.4, 1.56, 1.7, 1.83 ms
```
Both seems to scale linearly but the new one has a worse slope.
Figure 5

**Review by SimonHeybrock — APPROVED** [review]

**Pull request merged**
