### PR TITLE
Change plotting to not activate widget backend by default

### PR DESCRIPTION
**Pull request by nvaytet**
From the beginning of adding plotting to Scipp, we thought it would be best if figures were interactive by default in Jupyter notebooks, avoiding the need for users to type `%matplotlib widget` at the top of every notebook.

However, activating the widget backend by default has led to a number of issues.

- The interaction with other (raw) matplotlib figures was unpredictable, depending on the version of matplotlib, and the order of importing scipp and matplotlib (see for instance https://github.com/matplotlib/matplotlib/issues/19032)
- Mpl figures sometimes show up twice in the docs pages.

Current strange behaviour:
- if we import `matplotlib.pyplot` before or after `scipp` (order does not matter), if we try to make a pure Scipp plot, we have the widget backend.
- If we make a mpl plot first, and then a pure scipp plot, we get a blank canvas and a static figure below.
- If we try to make some mpl axes, and attach a scipp plot to it, we get a static figure, even though `plt.get_backend()` says that we are using the `ipympl` backend...

Additional complications:
- In the docs, we wanted to output static figures, but also show the buttons, sliders (which could be confusing, as the widgets had no effect on the plot)
- Our docs build required sphinx to pass a variable called `is_docs_build`, which was used in the plot `__init__.py`

Because of the above reaons, in this PR, we simplify the behaviour and just use the default matplotlib behaviour.
Default backend is inline. If a user wants interactive figures, they will need to type `%matplotlib widget` at the top of their notebook.

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
Should we make this breaking change for the old plotting code? It will mean we breaker user (experience) twice (second time when switching to now plotting). Have you considered making this change only for the new plotting?

**Comment by SimonHeybrock** [comment]
> > Have you considered making this change only for the new plotting?
> 
> Yes, that was my initial idea. But then I don't know how to fix the issues pointed out by @jl-wynen (static figure and blank canvas when you make a mpl plot first, and static fig when using existing mpl axes).

Is this an urgent fix?

We should keep in mind that user are probably willing to "accept" a certain frequency of breaking changes, but not more than that, so we should consider this carefully for such a "core" feature. But maybe it is not so bad (i.e., breaking), since plots will still show up?

**Comment by nvaytet** [comment]
Ok, I am fine with not fixing it now.

**Comment by nvaytet** [comment]
Should I try to fix the docs though?

**Comment by SimonHeybrock** [comment]
Oh :(
Then I suppose we should go ahead with this?

**Comment by nvaytet** [comment]
It appears that you can configure Jupyter to start the widget backend on startup.

You can make a python file in `/home/user/.ipython/profile_default/startup` that contains
```Py
from IPython import get_ipython

ipy = get_ipython()
ipy.run_line_magic('matplotlib', 'widget')
```

Maybe that's good enough?

**Comment by nvaytet** [comment]
New considerations:
The snippet above would throw an error if you try to start an `ipython` shell (i.e. not a notebook).
So we need an additional check that we are in fact running inside a notebook.

This extra check was causing importing scipp to be slow. Would this mean that every time we restart the kernel there would be a long wait?

**Comment by nvaytet** [comment]
Use `try/except`?

**Comment by jl-wynen** [comment]
Sounds like it is the user's responsibility to find a way to activate interactive mode if they want it.
We could add an option to our config file to switch to interactive mode whenever `sc.plot` is called. That would help users a bit. But it could be surprising that calling our plot function changes how matplotlib plots are handled.

**Comment by nvaytet** [comment]
@SimonHeybrock @jl-wynen
What should we do with this one?
I think I agree with

> But it could be surprising that calling our plot function changes how matplotlib plots are handled.

**Comment by nvaytet** [comment]
@SimonHeybrock I went back to passing an option to the ipython kernal via
```
nbsphinx_execute_arguments = [
    "--Session.metadata=scipp_sphinx_build=True",
]
```
in the `docs/conf.py` file, when wanting to use the widget backend inside a sphinx build.

Can you take another look? Make sure the generated docs look ok everywhere?

**Review by jl-wynen — APPROVED** [review]
LGTM

**Comment by SimonHeybrock** [comment]
Shouldn't this be explained in the https://scipp.github.io/visualization/plotting-overview.html page? Note every scipp user is fluent with Matplotlib in notebooks. Now it seems they have to read between the lines?

**Comment by nvaytet** [comment]
> Shouldn't this be explained in the https://scipp.github.io/visualization/plotting-overview.html page? Note every scipp user is fluent with Matplotlib in notebooks. Now it seems they have to read between the lines?

See https://github.com/scipp/scipp/pull/2754

**Pull request merged**
