### PR TITLE
Trivial Python export testing

### PR DESCRIPTION
**Pull request by DanNixon**
Re #986.

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
I think this makes sense. Is there anything that needs to be done to avoid the ensueing exceptions from causing test failures or unnecessary output.

**Comment by DanNixon** [comment]
> I think this makes sense. Is there anything that needs to be done to avoid the ensueing exceptions from causing test failures or unnecessary output?

Yes, I've added a simple wrapper that will catch the specific exception raised when a valid export cannot be found.

**Comment by SimonHeybrock** [comment]
I resolved some merge conflicts, hope that worked.

**Comment by DanNixon** [comment]
> In the future, is it worth putting tests of many related trivial functions into the same test? Better readability, since it is just one-liners?

Quite possibly, I kept them in the same location for now since this was more just proof that they worked (there are still more tests that fall into this category).
Would you see two test files per module in that case? `test_xyz.py` and `test_xyz_trivial.py`?

**Comment by SimonHeybrock** [comment]
> Or do you mean have a single test function for all trivial tests?

Not for all, but at least for "groups", such as all binary operations, all trigonometric, ...

**Pull request merged**
