### PR TITLE
Remove need for bins property in sc.histogram and sc.bin

### PR DESCRIPTION
**Pull request by SimonHeybrock**
As discussed earlier, see added ADR.

### CODE REVIEW

**Review by OwenArnold — APPROVED** [review]
Looks good and +1 for the ADR inclusion. 

Please immediate check/correct down-stream packages, in particular `ess-notebooks` that could well break because of these updates.

**Comment by SimonHeybrock** [comment]
> Please immediate check/correct down-stream packages, in particular `ess-notebooks` that could well break because of these updates.

Do we have any notebooks there using event data?

**Comment by OwenArnold** [comment]
> > Please immediate check/correct down-stream packages, in particular `ess-notebooks` that could well break because of these updates.
> 
> Do we have any notebooks there using event data?

I had thought that this was, but on inspection, it's not https://scipp.github.io/ess-notebooks/sans-reduction.html

**Comment by SimonHeybrock** [comment]
> > > Please immediate check/correct down-stream packages, in particular `ess-notebooks` that could well break because of these updates.
> > 
> > 
> > Do we have any notebooks there using event data?
> 
> I had thought that this was, but on inspection, it's not https://scipp.github.io/ess-notebooks/sans-reduction.html

On the contrary: I believe this was broken by having previously introduced the need for `.bins`, so now it should be "fixed" and work again with event data?

**Pull request merged**
