### PR TITLE
Fix broken compat tests

### PR DESCRIPTION
**Pull request by OwenArnold**
`test_mantid.py` not updated as part of #894

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
Actually these tests have been / are being moved to https://github.com/scipp/scipp-ci-mantid. Maybe now would be a good time to remove these here?

**Comment by DanNixon** [comment]
> Actually these tests have been / are being moved to [scipp/scipp-ci-mantid](https://github.com/scipp/scipp-ci-mantid).

I didn't realise these tests would mover over there too, I got the impression that repo was for testing equivalence of operations (Mantid algorithm level) and workflows.

I'm against moving the compat tests (at least all of them) there since they are actually testing Scipp code.

**Comment by SimonHeybrock** [comment]
@DanNixon Aren't the equivalence test also testing scipp code? I see your point about moving them, but the problem is that `scipp/scipp` CI is not setup to run these. Should we either have all or none of the Mantid-dependent tests in `scipp/scipp`?

**Comment by DanNixon** [comment]
> Aren't the equivalence test also testing scipp code?

Not in the way I meant in my previous comment. An equivalence test would be testing something we already test in the "standard" scipp test (e.g. `transform`) wheras the compat tests (i.e. tests of `compat.mantid.load`) are the only test of the workspace loading code.

(slightly off topic but I think out CI needs a proper discussion as I feel the Mantid CI solution is not ideal and is only adding to the fragmentation and maintainability problems we are already seeing)

**Comment by SimonHeybrock** [comment]
So are you suggesting all our build servers should have Mantid, so they can run these tests?

**Comment by DanNixon** [comment]
> So are you suggesting all our build servers should have Mantid, so they can run these tests?

No, the build environment should be containerised so it can run whatever it needs to (Mantid, Conda, Sphinx, etc...).

There is a point on the developer meeting to discuss this, I'd rather discuss this in detail then.

**Comment by SimonHeybrock** [comment]
> No, the build environment should be containerised so it can run whatever it needs to (Mantid, Conda, Sphinx, etc...).

That's what https://github.com/scipp/scipp-ci-mantid is, essentially. Where tests should be placed is another question I suppose.

**Comment by DanNixon** [comment]
> > No, the build environment should be containerised so it can run whatever it needs to (Mantid, Conda, Sphinx, etc...).
> 
> That's what [scipp/scipp-ci-mantid](https://github.com/scipp/scipp-ci-mantid) is, essentially. Where tests should be placed is another question I suppose.

No, that is an additional CI service is the sea of services we already use. We need to think about what we actually need and design a pipeline around that then choose an appropriate solution.

**Pull request merged**
