### PR TITLE
Table for new python interface

### LINKED ISSUE #269: Jupyter + table render support for new Dataset
Once #253 is done, make `scippy.table` work again.

### PR DESCRIPTION
**Pull request by nvaytet**
Made the `table.py` file compatible with the new python interface.

To test:
```Python
import numpy as np
import scippy as sp
d = sp.Dataset()
N = 10
d.set_coord(sp.Dim.Tof, sp.Variable([sp.Dim.Tof], values=np.arange(N+1).astype(np.float64), unit=sp.units.us, variances=0.1*np.random.rand(N+1)))
d['Counts'] = sp.Variable([sp.Dim.Tof], values=10.0*np.random.rand(N))
d['Sample'] = sp.Variable([sp.Dim.Tof], values=10.0*np.random.rand(N), unit=sp.units.m, variances=np.random.rand(N))
d['Scalar'] = sp.Variable(1.2)
v = sp.Variable([sp.Dim.Tof], values=np.arange(N).astype(np.float64), unit=sp.units.us, variances=0.1*np.random.rand(N))
sp.table(d)
sp.table(v)
```

Output:
Screenshot at 2019-07-09 00-18-54

Fixes #269

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
Thanks for adding unit tests!

One comment: There does not seem to be a way to tell the difference between coords and data, e.g., "Tof" and " Sample" in your screenshot? Maybe just write `coord[Dim.Tof]` or something like that?

**Comment by SimonHeybrock** [comment]
Or add another header line, containing `| coords | labels | data | attrs |`?

**Comment by nvaytet** [comment]
what about something like this? or is it too much?
Screenshot at 2019-07-11 15-26-22

**Comment by SimonHeybrock** [comment]
Looks good.

**Pull request merged**
