### PR TITLE
Sort by values

### PR DESCRIPTION
**Pull request by TC5027**
I added the possibility to sort a Variable instance according to its values along a specified dimension.
An example of use could be : `v = sc.Variable(['y','x'], values=np.array([[1,3,2],[4,0,5]]))` `sc.sort(v,'x')`
which would produce a Variable with values : [[1,2,3],[0,4,5]]. 
Note : the specified dimension is always swapped to the last place if necessary because of my recursive approch to perform the sort. It means that `sc.sort(sc.Variable(['y','x'], values=np.array([[1,3,2],[4,0,5]])), 'y')` will produce a Variable with values : [[1,4],[0,3],[2,5]] .

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
Hi Thibault, thanks for the contribution. A couple of thoughts:

- Variances appear to be lost?
- Swapping dimensions does not feel to be a nice behavior for an API (but see next point)?
- Do you actually require sorting by dimensions that are not the inner dimension at this point? If not, we can do more generic, faster, and simpler based on `subpan_view` and `transform`, see code example.

```cpp
# include "scipp/variable/subspan_view.h"
# include "scipp/variable/transform.h"

// example for in-place sort, could also make a version returning a copy
void sort(const VariableView &var, const Dim dim) {
  transform_in_place<std::tuple<double, float, int64_t, int32_t, bool>>(
      subspan_view(var, dim),
      transform_flags::expect_no_variance_arg<0>, // can also support this, need if constexpr in lambda
      overloaded{
          [](auto &range) { std:sort(range.begin(), range.end()); },
          [](units::Unit &) {}});
```

I recommend to read https://scipp.github.io/developer/transform.html on how `transform` works. In particular also the last part about putting the internals into `core::element` (not inline as in the example I put above).

**Comment by SimonHeybrock** [comment]
@TC5027 I'd be happy to discuss details of my suggestion in a video call if you like, just get in touch!

**Comment by SimonHeybrock** [comment]
One more thought: We have recently added `is_sorted`: https://github.com/scipp/scipp/blob/9c4f2bdda9fa67a725423cada895197145b15ed2/variable/include/scipp/variable/util.h#L20-L23

- Should also support ascending/descening in `sort`, so it is equivalent (use the same enum).
- This can also be used for unit test, e.g., `EXPECT_TRUE(is_sorted(sort(var, dim), dim))`.

**Comment by TC5027** [comment]
Indeed the variances are not handled, I will look into this. A video call sounds like a good idea to me, I have questions about span's concept and the `overloaded` function. I'm not working tomorrow but next week I'm free if it's ok for you ? I have slack for the video call. My mail : chatel@ill.fr

**Comment by TC5027** [comment]
I was thinking about sorting along inner dimensions only but I want to be sure that what I imagine being inner dimension is correct, maybe we will talk about this during the call.

**Comment by SimonHeybrock** [comment]
@TC5027 Next week should work for me. Are you on the Mantid Slack workspace? I cannot find you.

**Comment by TC5027** [comment]
I'm not on the mantid slack workspace, you can just send me a zoom invitation on my webmail adress I guess

**Comment by SimonHeybrock** [comment]
Closing in favor of new approach in #1288.

**Pull request closed without merging**
