### PR TITLE
Version selection menu in docs

### PR DESCRIPTION
**Pull request by nvaytet**
This adds a small dropdown menu at the bottom of the navigation sidebar that provides easy access to the doc pages for the different releases.

There is a 32px high padding area at the bottom of the navigation sidebar, so I overlayed a `div` with `position: fixed; bottom: 0;` on top of this padding.

Right now, when changing version, this will re-direct you to the top level page, and not a different version of the page you are currently viewing. We could make this work with something a bit more advanced, but I think it's probably good enough for a first pass.
In addition, some pages might not exist in the older releases, so linking to that could cause errors.

### CODE REVIEW

**Review by matthew-d-jones — APPROVED** [review]
Looks good to me.
As @jl-wynen pointed out, it is usually floating on the bottom right of the page rather than at the bottom of the menu on the left. Maybe worth checking if that is easy to achieve, but this is good enough if not.

**Review by DanNixon — APPROVED** [review]

**Comment by jl-wynen** [comment]
> As @jl-wynen pointed out, it is usually floating on the bottom right of the page rather than at the bottom of the menu on the left. Maybe worth checking if that is easy to achieve, but this is good enough if not.

Not quite what I meant. E.g. look at this: https://pybind11.readthedocs.io/en/stable/
Here it is on the right _of the menu_ not of the entire page.

**Comment by nvaytet** [comment]
> Looks good to me.
> As @jl-wynen pointed out, it is usually floating on the bottom right of the page rather than at the bottom of the menu on the left. Maybe worth checking if that is easy to achieve, but this is good enough if not.

It's at the right of the side navigation bar, not the whole page:
Screenshot at 2021-01-05 14-22-33

**Comment by matthew-d-jones** [comment]
> > As @jl-wynen pointed out, it is usually floating on the bottom right of the page rather than at the bottom of the menu on the left. Maybe worth checking if that is easy to achieve, but this is good enough if not.
> 
> Not quite what I meant. E.g. look at this: https://pybind11.readthedocs.io/en/stable/
> Here it is on the right _of the menu_ not of the entire page.

oh, I was looking at https://faust.readthedocs.io/en/latest/ where it is actually floating on the right.

**Comment by nvaytet** [comment]
Different theme ;-)

**Pull request merged**
