### PR TITLE
Erasing coords labels attrs

### LINKED ISSUE #564: Erasing coords/labels/attrs
We are missing `erase` and `__delitem__` for coords, etc. The current implementation only support removing data items using:

```python
del d['abc']
```

We are missing

```python
del d.coords[Dim.X]
```
and the C++ equivalent.

### PR DESCRIPTION
**Pull request by igudich**
fixes #564

### CODE REVIEW

**Comment by igudich** [comment]
> Looks good, but need to add erase also for coords/labels/attrs of `DataArray`.

Is it really worth to do so? You always can do:
```c++
data_array.coords().erase(...);
data_array.labels().errase(...);
```
Is introducing the another API meaningful in this case?

**Comment by SimonHeybrock** [comment]
> > Looks good, but need to add erase also for coords/labels/attrs of `DataArray`.
> 
> Is it really worth to do so? You always can do:
> 
> ```c++
> data_array.coords().erase(...);
> data_array.labels().errase(...);
> ```
> 
> Is introducing the another API meaningful in this case?

So you are saying the methods like `eraseCoord()` on `Dataset` are just implementation details and should not be used externally? I think that is ok.

**Comment by igudich** [comment]
> > > Looks good, but need to add erase also for coords/labels/attrs of `DataArray`.
> > 
> > 
> > Is it really worth to do so? You always can do:
> > ```c++
> > data_array.coords().erase(...);
> > data_array.labels().errase(...);
> > ```
> > 
> > 
> > Is introducing the another API meaningful in this case?
> 
> So you are saying the methods like `eraseCoord()` on `Dataset` are just implementation details and should not be used externally? I think that is ok.

Yes, I can hide `eraseCoord` into some friend function in `detail` workspace, but then I should do the same for all `setXXX` to make things consistent, should we make all proxies `friends` to `Variable` or even move all the definitions to the there?

**Comment by SimonHeybrock** [comment]
> Yes, I can hide `eraseCoord` into some friend function in `detail` workspace, but then I should do the same for all `setXXX` to make things consistent, should we make all proxies `friends` to `Variable` or even move all the definitions to the there?

I think we can leave it as it is. There is no harm in having them (no misuse possible), and you cannot see them in Python anyway, so `friend` would probably be overkill now.

If you want, you can just put a note in the Doxygen of `eraseCoord` etc. that recommends to erase via the proxy instead?

**Comment by SimonHeybrock** [comment]
@igudich I think you need to update your clang-format to version 6.

**Comment by SimonHeybrock** [comment]
@igudich We merged masking support yesterday (see #589), could you please add support for erasing masks as well? This works exactly like all the others (coords, labels, and attrs) so it should be trivial.

**Comment by igudich** [comment]
> @igudich We merged masking support yesterday (see #589), could you please add support for erasing masks as well? This works exactly like all the others (coords, labels, and attrs) so it should be trivial.

What about sparse masks, I mean no masks in `DatasetData`? Or do we postpone this to the better times?

**Comment by SimonHeybrock** [comment]
We are not supporting sparse masks. I am not aware of a requirement for that right now. So, yes, postponed untie needed (if ever).

**Pull request merged**
