### PR TITLE
Hide profile plot axes in docs

### PR DESCRIPTION
**Pull request by nvaytet**
Before:
Screenshot at 2021-01-06 13-01-06

After:
Screenshot at 2021-01-06 13-01-24

### CODE REVIEW

**Comment by jl-wynen** [comment]
Would it make sense to hide the buttons, too? Or disable them visibly in some way (e.g. gray out)? It still looks like they are active when you hover over them.

**Comment by nvaytet** [comment]
hmm it's a good point.
We want to show the widgets in the docs, because we talk about widgets (sliders etc...) and it's good for representing what the plots really look like.

However, when not building the docs, if a user decides to use the `inline` backend (with `%matplotlib inline` in a notebook cell), the widgets should not show up.
That was the entire point of the `is_docs_build` variable in the `__init__.py`.
Now it seems it's not being used anymore....

**Comment by OwenArnold** [comment]
Can the widgets be made to appear in the docs but otherwise be disabled? 
image

**Review by OwenArnold — COMMENTED** [review]
Code looks ok to me.

**Comment by nvaytet** [comment]
With the latest changes, all widgets including the figure toolbar (home, zoom) appear in the docs but all are hidden in notebooks when using inline backend.

You can try in a notebook with `%matplotlib inline` or by setting `sc.plot.is_doc_build = True` to see the 2 different behaviors

**Pull request merged**
