### PR TITLE
Demo Docker image update

### LINKED ISSUE #274: Update Dockerfile and docker image
- Create script for making docker image, document it somewhere.
- Does it make sense to setup Travis (using https://docs.travis-ci.com/user/cron-jobs/) to build a new image once a week or so?

### PR DESCRIPTION
**Pull request by DanNixon**
See commit messages.

Fixes #274.

A script to automatically deploy this isn't done yet, first we should decide:
- will building and deployment be done entirely automatically or both automatically and manually?
- what label format should be used?  
  (my vote would be pushing the existing image under the `legacy` or `0.0.1` tag and using `latest` for automatic pushes going forward)

As building and publishing this is relatively quick it might be acceptable to add this as a stage after the Conda deployment.

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
>     * will building and deployment be done entirely automatically or both automatically and manually?

Both. I suggest we use Travis' `cron`, but also need to be able to trigger this manually.

>     * what label format should be used?
>       (my vote would be pushing the existing image under the `legacy` or `0.0.1` tag and using `latest` for automatic pushes going forward)

I'd say we register `scipp` on dockerhub, the current `dmsc-id` organization is too hard to remember. `latest` sounds good.

> As building and publishing this is relatively quick it might be acceptable to add this as a stage after the Conda deployment.

How quick? We are already pushing the free Travis plan sometimes, I think. Maybe `cron` is more suitable for now?

**Comment by DanNixon** [comment]
> > ```
> > * what label format should be used?
> >   (my vote would be pushing the existing image under the `legacy` or `0.0.1` tag and using `latest` for automatic pushes going forward)
> > ```
> 
> I'd say we register `scipp` on dockerhub, the current `dmsc-id` organization is too hard to remember. `latest` sounds good.

Cool, I think for now if you are happy with these changes I'll leave this PR as it is (obviously things like the demo notebooks won't work yet).
The scripts can be added once a new user/organisation has been created so there is somewhere sensible for it to push them.

> > As building and publishing this is relatively quick it might be acceptable to add this as a stage after the Conda deployment.
> 
> How quick? We are already pushing the free Travis plan sometimes, I think. Maybe `cron` is more suitable for now?

Probably just a couple of minutes.

**Comment by SimonHeybrock** [comment]
Would it make sense to provide a "minimal" scipp docker in addition to the one that has Mantid?

**Comment by SimonHeybrock** [comment]
Merging. Can update CI later.

**Comment by DanNixon** [comment]
> Would it make sense to provide a "minimal" scipp docker in addition to the one that has Mantid?

Probably not IMO, the only advantage it would have is filesize and I'm not sure that the overhead of maintaining two versions is worth it.

**Pull request merged**
