### PR TITLE
Check if arguments share a buffer in sort

### PR DESCRIPTION
**Pull request by jl-wynen**
Calling sort with a key that matches the data or at least partially overlaps it can cause an infinite loop.

The check added here is pretty crude, one could check  for an actual overlap. See the added tests, they pass even though those particular cases would be fine in practice.

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
Can you elaborate where the infinite loop comes in? I cannot tell from looking at the code.

**Comment by jl-wynen** [comment]
When the sort key overlaps the data you want to sort, then moving data elements around also moves the key's elements. This on its own can cause the result to be wrong. And what I noticed is that it can cause an infinite loop where elements are swapped back and forth.

**Comment by SimonHeybrock** [comment]
Yes, but that is the point I do not understand: The implementation is using `groupby` and iirc it is not using the key directly in the "combine" step, instead work based on a slice->group mapping. Also, it is not doing an in-place sort, so where is the reorder problem coming from?

**Comment by jl-wynen** [comment]
Not actually an issue. I misunderstood the bug and the solution does not do anything useful.

**Pull request closed without merging**
