### PR TITLE
Python module configuration file

### LINKED ISSUE #758: Config / settings file
Scipp has some options for customization. Currently this is mainly plotting styles. To make this persistent we need some sort of (cross platform) config-file mechanism, e.g., for storing things in `~/.scipp/` on Linux.

Probably this is only required on the Python side?

### PR DESCRIPTION
**Pull request by DanNixon**
Fixes #758.

### CODE REVIEW

**Comment by DanNixon** [comment]
@nvaytet The plotting unit tests run and I don't think I've missed any uses of the old config. As you know more of the plotting than me can you make sure nothing is broken?

**Comment by nvaytet** [comment]
it looks good, and I don't think you need to change the notebooks, e.g. here: https://scipp.readthedocs.io/en/latest/visualization/plotting-in-depth.html#Image-aspect-ratio
because the syntax is the same: `sc.config.plot.aspect = "equal"`

builds are failing though :-(

**Comment by DanNixon** [comment]
> I don't think you need to change the notebooks, e.g. here: [scipp.readthedocs.io/en/latest/visualization/plotting-in-depth.html#Image-aspect-ratio](https://scipp.readthedocs.io/en/latest/visualization/plotting-in-depth.html#Image-aspect-ratio)
> because the syntax is the same: `sc.config.plot.aspect = "equal"`

Maybe worth mentioning that changes via the API will not persist at least.

> builds are failing though :-(

Yes, looking into that now.

**Comment by DanNixon** [comment]
This will have to wait until `python-configuration` is Conda installable.

See https://github.com/conda-forge/staged-recipes/pull/10610

**Comment by DanNixon** [comment]
@nvaytet This is ready for another test now. Note that if you use a locally built Conda package you will have to install the extra dependencies manually (dependency resolution is not performed when installing from a tar archive).

**Comment by SimonHeybrock** [comment]
> This will have to wait until `python-configuration` is Conda installable.
> 
> See [conda-forge/staged-recipes#10610](https://github.com/conda-forge/staged-recipes/pull/10610)

Are you saying this should not be merged yet, or is "this" referring to something else?

**Comment by DanNixon** [comment]
> > This will have to wait until `python-configuration` is Conda installable.
> > See [conda-forge/staged-recipes#10610](https://github.com/conda-forge/staged-recipes/pull/10610)
> 
> Are you saying this should not be merged yet, or is "this" referring to something else?

No, this can be merged. The required dependencies are now in conda-forge.

**Comment by nvaytet** [comment]
Just one thing: we probably have to document that there is now a config file that users can modify to get persistent changes.

**Comment by DanNixon** [comment]
> Just one thing: we probably have to document that there is now a config file that users can modify to get persistent changes.

Yes, I'll take a look at adding something now.

**Pull request merged**
