### PR TITLE
Travis for macOS and remove unused bindings for Dimensions

### LINKED ISSUE #336: Travis macOS build
We need a conda package for macOS. Luckily Travis also provides free macOS builds, so we should use those.

An additional advantage would be to avoid breaking mac-clang builds, which appears to have a number of differences to the linux-clang builds.

### PR DESCRIPTION
**Pull request by OwenArnold**
Fixes #336.

### CODE REVIEW

**Comment by OwenArnold** [comment]
Enable ccache cross platform - described in detail here https://crascit.com/2016/04/09/using-ccache-with-cmake/

**Comment by OwenArnold** [comment]
@SimonHeybrock looks like `test_lifetime` is failing. Test suggests `Dimensions` should be kept alive, but looks like that's not happening.

**Comment by SimonHeybrock** [comment]
> @SimonHeybrock looks like `test_lifetime` is failing. Test suggests `Dimensions` should be kept alive, but looks like that's not happening. Any ideas on how to extend lifetime, or why lifetime extension is not working? Maybe a missing `keep_alive` on `Dimensions`?

We have had this before, but I do not know what is going on now: `shape` is defined using `def_property_readonly`. https://pybind11.readthedocs.io/en/stable/advanced/functions.html?highlight=keep_alive#return-value-policies explains:

> 

return_value_policy::reference_internal | Indicates that the lifetime of the return value is tied to the lifetime of a parent object, namely the implicit this, or self argument of the called method or property. Internally, this policy works just like return_value_policy::reference but additionally applies a keep_alive<0, 1> call policy (described in the next section) that prevents the parent object from being garbage collected as long as the return value is referenced by Python. This is the default policy for property getters created via def_property, def_readwrite, etc.
-- | --

So this should work, if I understand correctly?

I suggest you try applying the policy manually. If that doesn't work, do what I am currently doing here:

https://github.com/scipp/scipp/blob/b5a43f269c24e8a0898ef7ed776e35099dda8cd3/python/bind_data_access.h#L274-L279

**Comment by SimonHeybrock** [comment]
Regarding the failed tests, I think you need to remove the forward-declared call to `init_dimensions` in `python/scipp.cpp`

**Pull request merged**
