### PR TITLE
Update string representations

### PR DESCRIPTION
**Pull request by jl-wynen**
- Changes 'Coordinates (Unaligned)' to 'Attributes' in string output of DataArray and Dataset.
- Changes indentation of attributes and masks to match that of HTML tables.

Masks and attributes not indented:
```.py
da = sc.DataArray(
    coords={'x': sc.Variable(['x'], values=np.arange(10), unit=sc.units.m),
            'lab': sc.Variable(['x'], values=np.arange(11), unit=sc.units.m)},
    attrs={'a1': sc.Variable(['x'], values=1.1*np.arange(11), unit=sc.units.m),
           'a2': sc.Variable(['x'], values=1.2*np.arange(10), unit=sc.units.m)},
    masks={'m1': sc.Variable(['x'], values=np.arange(10)%2==0)},
    data=sc.Variable(['x'], values=np.random.random(10), unit=sc.units.counts))
print(da)
```
```
<scipp.DataArray>
Dimensions: {{x, 10}}
Coordinates:
    lab                       int64      [m]              (x [bin-edges])  [0, 1, ..., 9, 10]
    x                         int64      [m]              (x)  [0, 1, ..., 8, 9]
Data:
                              float64    [counts]         (x)  [0.310651, 0.220707, ..., 0.205225, 0.407591]
Masks:
    m1                        bool       [dimensionless]  (x)  [True, False, ..., True, False]
Attributes:
    a1                        float64    [m]              (x [bin-edges])  [0.000000, 1.100000, ..., 9.900000, 11.000000]
    a2                        float64    [m]              (x)  [0.000000, 1.200000, ..., 9.600000, 10.800000]
```

Masks and attributes indented:
```.py
ds = sc.Dataset()
ds.coords['x'] = sc.Variable(['x'], values=np.arange(10), unit=sc.units.m)
ds.coords['lab'] = sc.Variable(['x'], values=np.arange(11), unit=sc.units.m)
ds['Signal'] = sc.Variable(['x'], values=np.random.random(10), unit=sc.units.m)
ds['Signal'].attrs['a1'] = sc.Variable(['x'], values=1.1*np.arange(11), unit=sc.units.s)
ds['Signal'].attrs['a2'] = sc.Variable(['x'], values=1.2*np.arange(10), unit=sc.units.s)
ds['Signal'].masks['m1'] = sc.Variable(['x'], values=np.arange(10)%2==0)
print(ds)
```
```
<scipp.Dataset>
Dimensions: {{x, 10}}
Coordinates:
    lab                       int64      [m]              (x [bin-edges])  [0, 1, ..., 9, 10]
    x                         int64      [m]              (x)  [0, 1, ..., 8, 9]
Data:
    Signal                    float64    [m]              (x)  [0.447900, 0.001226, ..., 0.769538, 0.259266]
    Masks:
            m1                        bool       [dimensionless]  (x)  [True, False, ..., True, False]
    Attributes:
            a1                        float64    [s]              (x [bin-edges])  [0.000000, 1.100000, ..., 9.900000, 11.000000]
            a2                        float64    [s]              (x)  [0.000000, 1.200000, ..., 9.600000, 10.800000]
```

### CODE REVIEW

**Comment by nvaytet** [comment]
In the case of the Dataset, I think the masks and the attributes should be indented further.

If you have two entries in your dataset, you would want to make it obvious to which entry the masks belong to, e.g.
```
<scipp.Dataset>
Dimensions: {{x, 10}}
Coordinates:
    lab                       int64      [m]              (x [bin-edges])  [0, 1, ..., 9, 10]
    x                         int64      [m]              (x)  [0, 1, ..., 8, 9]
Data:
    Entry_a                    float64    [m]              (x)  [0.447900, 0.001226, ..., 0.769538, 0.259266]
        Masks:
                m_a                        bool       [dimensionless]  (x)  [True, False, ..., True, False]
        Attributes:
                a1_a                        float64    [s]              (x [bin-edges])  [0.000000, 1.100000, ..., 9.900000, 11.000000]
                a2_a                        float64    [s]              (x)  [0.000000, 1.200000, ..., 9.600000, 10.800000]
    Entry_b                    float64    [m]              (x)  [0.447900, 0.001226, ..., 0.769538, 0.259266]
        Masks:
                m_b                        bool       [dimensionless]  (x)  [True, False, ..., True, False]
        Attributes:
                a1_b                        float64    [s]              (x [bin-edges])  [0.000000, 1.100000, ..., 9.900000, 11.000000]
                a2_b                        float64    [s]              (x)  [0.000000, 1.200000, ..., 9.600000, 10.800000]
```

**Comment by jl-wynen** [comment]
That would not be consistent with DataArray. 
And since we have very limited real estate do begin with, I'd rather keep it the way it is in both cases.

**Comment by nvaytet** [comment]
Data array doesn't need it because it only ever has one entry. The real estate should be saved elsewhere with either only 2 spaces instead of 4 and reducing the number of decimal places for the numbers printed

**Comment by nvaytet** [comment]
Note that the length of the lines would be the same as current because you have 8 spaces before the masks variables instead of 4 elsewhere

**Comment by nvaytet** [comment]
To save space we could reduce the number of white spaces between the variable names and the data type?

**Comment by jl-wynen** [comment]
Better?

I could make it so that the output is aligned nicely; similar to the HTML representations. But that would take some time. Do we care about this enough?

**Comment by nvaytet** [comment]
Fine for now, thanks for doing this.

**Review by nvaytet — APPROVED** [review]

**Pull request merged**
