### PR TITLE
Add `sizes` argument to `zeros`, `ones` and `empty`

### PR DESCRIPTION
**Pull request by nvaytet**
Add optional `sizes` arguments to `sc.zeros`, `sc.ones`, `sc.empty` that can be used instead of `dims` and `shape`.

### CODE REVIEW

**Comment by jl-wynen** [comment]
I don't think it is a good idea to add a top level `random` function. If in the future we want to support more advanced RNGs like numpy, we should have a module called random.

**Comment by nvaytet** [comment]
> If in the future we want to support more advanced RNGs like numpy, we should have a module called random.

On one hand, I agree that this would probably be a more 'correct' way of doing things.

But on the other hand, I'm also thinking about user experience and ease of use. I've always been kind of bothered by having to do `np.random.random()` and then is it `np.random.random()` or `np.random.rand()`? (which have slightly different interfaces, and i can never remember which is which).

I think most of the time, this will be used to just quickly generate some random data. If you want an accurate control about which generator you want to use, because it is important for the application, then you can just use numpy to properly generate your data.

If we want to add more generators in the future, maybe we could also do it with a keyword arg, to select a generator?

I am not sure we will be developing a full library for random data (as it's mostly useful for making fake data for tests and docs where the actual random distribution is not of paramount importance) and I am not sure it is worthy of its own submodule in scipp?

**Comment by jl-wynen** [comment]
> and then is it np.random.random() or np.random.rand()

This is historical, we should not do it.

> If we want to add more generators in the future, maybe we could also do it with a keyword arg, to select a generator?

How would you support generator specific arguments? `sc.random(distribution='gaus', mean=1, sigma=0.1)` vs `sc.random(distribution='uniform', low=-1, high=1)` Seems pretty messy. (Also at the very least we need the `low` and `high` args for the uniform generator.

> as it's mostly useful for making fake data for tests and docs where the actual random distribution is not of paramount importance

If you assume it is only used for neutron scattering. What about random sampling for error estimation or optimisation? What about theoretical / modeling applications?

Numpy now even recommends using generator objects (only a small paragraph on the old functions in https://numpy.org/doc/stable/reference/random/index.html) because global RNGs are risky to use. I generally agree with this choice. Random numbers are easy to get wrong. And in the case of your `sc.random`, the generator even has a hidden dependency on the global np generator. So a call to `np.random.seed` anywhere in your program can completely screw you over. All this is to say that I don't think it is a good idea to make random sampling too easy / convenient.

**Comment by SimonHeybrock** [comment]
> I am not sure we will be developing a full library for random data (as it's mostly useful for making fake data for tests and docs where the actual random distribution is not of paramount importance) and I am not sure it is worthy of its own submodule in scipp?

I would use your argument to argue exactly the opposite: If it is mainly for fake data for test and docs then it should absolutely *not* be a top-level function.

Whether you want to hide it in a submodule called `random` is a different question, but since that is the numpy naming this would be the least confusing option, imho.

**Comment by nvaytet** [comment]
Ok I see you guys think this should absolutely not go in scipp, so I'm just going to close this.

**Comment by SimonHeybrock** [comment]
I think we simply suggested to not make this a *top-level* function of the module. Instead put it into a submodule. Sorry if that was unclear.

**Comment by SimonHeybrock** [comment]
> Numpy now even recommends using generator objects (only a small paragraph on the old functions in https://numpy.org/doc/stable/reference/random/index.html) because global RNGs are risky to use. I generally agree with this choice. Random numbers are easy to get wrong. And in the case of your sc.random, the generator even has a hidden dependency on the global np generator. So a call to np.random.seed anywhere in your program can completely screw you over. All this is to say that I don't think it is a good idea to make random sampling too easy / convenient.

Good point. Maybe we should update our documentation to use the recommended way.

**Review by jl-wynen — APPROVED** [review]

**Pull request merged**
