### PR TITLE
Show to support bin edges of slices

### LINKED ISSUE #1499: Confusing error when showing DataArray with mismatch in coord dims
The call of `sc.show` in this example raises an `IndexError`.

```.py
import scipp as sc
import numpy as np

N = 10
var = sc.Variable(unit=sc.units.m, dims=['x'], values=np.random.normal(3, 5, N))
dset = sc.DataArray(var, coords={'asd': sc.Variable(dims=['y'], values=np.linspace(0, 1, N))})

sc.show(dset)
```
```
---------------------------------------------------------------------------

IndexError                                Traceback (most recent call last)

<ipython-input-6-5a189de14405> in <module>
      1 
----> 2 sc.show(dset)
      3 

~/Work/scipp-devel/install-release/scipp/show.py in show(container)
    453     """
    454     from IPython.core.display import display, HTML
--> 455     display(HTML(make_svg(container)))

~/Work/scipp-devel/install-release/scipp/show.py in make_svg(container)
    445     else:
    446         draw = DatasetDrawer(container)
--> 447     return draw.make_svg()
    448 
    449 

~/Work/scipp-devel/install-release/scipp/show.py in make_svg(self)
    381                 elif var.dims[-1] == dims[-1]:
    382                     area_x.append(item)
--> 383                 elif var.dims[-1] == dims[-2]:
    384                     area_y.append(item)
    385                 else:

IndexError: list index out of range
```

This happens whenever the `dims` of the coordinates differ from the `dims` of `var`.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
- Fixes #1499.
- Ensure `DataArray.coords` behaves like `DataArrayView.coords`, excluding coords that exceed data. I think this must have been intentional to handle the case of storing a bin-edge coords on a scalar (in that dimension) data array, but it is causing trouble here. Should revisit this with the ownership redesign, to see if we can do anything better.

Example to try:
```python
import scipp as sc
import numpy as np

data = sc.ones(dims=['x'], shape=[4])
edges = sc.ones(dims=['x'], shape=[5])
da = sc.DataArray(data, coords={'x':edges})
sc.show(da)
sc.show(da['x',3])
ds = sc.Dataset({'a':da})
ds.coords['y'] = sc.ones(dims=['y'], shape=[4])
ds.dims
sc.show(ds)
```

Results in: 
image

### CODE REVIEW

**Comment by jl-wynen** [comment]
This displays attributes with dimensions that are not in the data as though they were along the ndim+1-axis
attr

**Comment by SimonHeybrock** [comment]
> This displays attributes with dimensions that are not in the data as though they were along the ndim+1-axis
> attr

Yes, isn't that correct?

**Comment by jl-wynen** [comment]
It makes it look as though it was aligned with the data somehow.
And when the data is 3D, it says `RuntimeError: Cannot visualize 4-D data`

**Comment by SimonHeybrock** [comment]
> It makes it look as though it was aligned with the data somehow.

I don't think we should dump a lot of time into fixing alignment esoteric edge cases that may be disabled in the future.

> And when the data is 3D, it says `RuntimeError: Cannot visualize 4-D data`

Yes, because the implementation cannot visualize 4D data.

**Comment by jl-wynen** [comment]
> Yes, because the implementation cannot visualize 4D data.

Sure, but it means that such a dataset cannot be shown even though it is essentially only 3D. But if you see this case as esoteric, let's just leave it as is.

**Comment by SimonHeybrock** [comment]
> > Yes, because the implementation cannot visualize 4D data.
> 
> Sure, but it means that such a dataset cannot be shown even though it is essentially only 3D. But if you see this case as esoteric, let's just leave it as is.

Well, do you want to just not show those coords then?

**Comment by jl-wynen** [comment]
Maybe as in the dataset case above, put it next to the data?

**Comment by SimonHeybrock** [comment]
> Maybe as in the dataset case above, put it next to the data?

But if it goes into the 4th dimension that is impossible.

**Comment by jl-wynen** [comment]
Is the existing solution just aligned with dimension ndim+1 and then shifted?

Maybe put a list of such attributes to the right? But if they are disallowed in the future anyway, just leave it as is.

**Comment by SimonHeybrock** [comment]
> Is the existing solution just aligned with dimension ndim+1 and then shifted?

The implementation simply handles the object as if it had the union of data dims and meta-data dims. So if you have data in X and an attr in Y, it is 2-D, so the Y attr is shown vertically.

**Comment by nvaytet** [comment]
It's not a big deal but slightly strange that in the first example, before the `y` coord is added, the `x` coord is horizontal, but it becomes vertical when the `y` coords is added.
In Jan-lukas's example, the `x` coords stays horizontal and the non-dimension coordinate `asd` is vertical.
What's the reason.

**Comment by SimonHeybrock** [comment]
Dataset coord order is undefined.

**Comment by nvaytet** [comment]
> The implementation simply handles the object as if it had the union of data dims and meta-data dims. So if you have data in X and an attr in Y, it is 2-D, so the Y attr is shown vertically.

I think this makes sense because it will then try to align different dataset items that share some dims, e.g. if you have entry `a` that has dims `[x, y]` and entry `b` that has dims `[y, z]`.
Then it seems logical that when you encounter a new dim in a coordinate, you just represent it as if it were a new dimension of the dataset. Finding out if the dimension is just the odd one out in a DataArray, so you can put it on the side, sounds like it would make the code less generic.

In any case, I think this is a relatively rare edge case that we should probably not spend too much time worrying about.

**Pull request merged**
