### PR TITLE
Use underscores instead of hyphens in standard coord names

### LINKED ISSUE #1642: Naming convention for neutron-specific coords
We have previously switched to the convention:
- use `_` for subscripts, e.g. `E_i` or `Q_x`.
- use `-` (hyphen) the separate words.

However:
- This conflics with same conventions from Nexus.
- Variable names do not match coord names, e.g., `pulse_time = data.coords['pulse-time']`
- Would not be compatible if keyword args for `__getitem__` where supported in the future, e.g., `data[pulse_time=4]`.
- Would not allow defining properties from dict entries, e.g., `data.pulse_time` to access `data.coords['pulse-time']`.

Dicussion:
- Should we use `_` instead?

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Closes #1642. There will be an accompanying PR in scippneutron.

### CODE REVIEW

**Review by OwenArnold — APPROVED** [review]
beware this change may well break downstream projects such as `ess` and `ess-notebooks`

**Comment by jl-wynen** [comment]
Why are the scattering-specific names still in the core scipp?

**Comment by SimonHeybrock** [comment]
> Why are the scattering-specific names still in the core scipp?

On the C++ side dimension labels are stored using an index (not a string). For performance reasons (I think I had tried this in the orginal implementation) it is not using hashing, but has a partially hard-coded list of IDs. When using an unknown string label it will insert into a map, which involves a locking a mutex. Strictly speaking we could remove all hard-coded labels.

Note that it is an implementation detail which ones are actually builtin.

**Comment by SimonHeybrock** [comment]
The discussion whether we can avoid the neutron-specific builtin dim names here is independent of the changeset, so I'll merge this. Feel free to continue discussion elsewhere.

**Pull request merged**
