### PR TITLE
Set a sensible scipp.__version__ attribute

### PR DESCRIPTION
**Pull request by DanNixon**

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
I suppose our conda packages would lag one build behind in updating the version? So when we move to `0.1`, the first conda package built with it will still show the old version?

Is that a problem worth solving?

**Comment by DanNixon** [comment]
> I suppose our conda packages would lag one build behind in updating the version? So when we move to `0.1`, the first conda package built with it will still show the old version?

Why would that be the case?

Assuming we use GitHub releases we would publish via the web UI and trigger a build manually, `git describe --tag` would then report that we are at the latest tag with 0 commits ahead.

**Comment by SimonHeybrock** [comment]
> > I suppose our conda packages would lag one build behind in updating the version? So when we move to `0.1`, the first conda package built with it will still show the old version?
> 
> Why would that be the case?

We cannot tag a release before we merge into `master`. But the merge triggers the build of the (first) package that should have that version, i.e., happens before we have a chance to tag the merge commit?

**Comment by DanNixon** [comment]
> > > I suppose our conda packages would lag one build behind in updating the version? So when we move to `0.1`, the first conda package built with it will still show the old version?
> > 
> > 
> > Why would that be the case?
> 
> We cannot tag a release before we merge into `master`. But the merge triggers the build of the (first) package that should have that version, i.e., happens before we have a chance to tag the merge commit?

I didn't realise you had intended on using release branches. In that case you could either:
- merge and tag locally then convert the tag to a GH release via the web UI
- rebase the release branch and fast forward merge back to master, in which case the tag can be created from the release branch (I *think* this should work)
- merge with `[ci skip]` to avoid the build with the old version number

In any case as long as a build happens after the release is tagged the only thing lost is CI time.

**Pull request merged**
