### PR TITLE
Fix 2 issues with new h5py

### PR DESCRIPTION
**Pull request by SimonHeybrock**
See commits.

### CODE REVIEW

**Review by nvaytet — APPROVED** [review]

**Review by OwenArnold — COMMENTED** [review]
Is this a breaking change against older versions of h5py? If so can we update the minimum version in the environment files?

**Comment by SimonHeybrock** [comment]
> Is this a breaking change against older versions of h5py? If so can we update the minimum version in the environment files?

I think the envs just get the latest versions?

**Comment by SimonHeybrock** [comment]
I don't think it is breaking though. For the changed default file opening mode there was actually a deprecation warning in my old local version.

**Comment by OwenArnold** [comment]
> > Is this a breaking change against older versions of h5py? If so can we update the minimum version in the environment files?
> 
> I think the envs just get the latest versions?

Indeed they will. I can't see exactly how it could go wrong, but we could explicitly mark that we needed >=. If it

**Review by OwenArnold — APPROVED** [review]

**Pull request merged**
