### PR TITLE
Support event-mode scaling operations if only output has variances

### LINKED ISSUE #2400: Division of bins by Lookup fails if bins have variance but not Lookup
This
```python
import scipp as sc
events = sc.DataArray(
    sc.array(dims=['event'], values=[1., 2, 3], variances=[0.1, 0.2, 0.3]),
    coords={'x': sc.array(dims=['event'], values=[0., 1., 2.])})
da = sc.bin(events, edges=[sc.array(dims=['x'], values=[0.0, 1.0, 3.0])])

x = sc.linspace(dim='x', start=0.0, stop=1.0, num=4)
vals = sc.array(dims=['x'], values=[3., 2, 1])
hist = sc.DataArray(data=vals, coords={'x': x})

da.bins / sc.lookup(hist, 'x')
```
raises
```python
---------------------------------------------------------------------------
VariancesError                            Traceback (most recent call last)
/tmp/ipykernel_35848/284705867.py in <module>
      2 vals = sc.array(dims=['x'], values=[3., 2, 1])
      3 hist = sc.DataArray(data=vals, coords={'x': x})
----> 4 da.bins / sc.lookup(hist, 'x')

~/Software/mambaforge/envs/ess-1/lib/python3.9/site-packages/scipp/core/bins.py in __truediv__(self, lut)
     69     def __truediv__(self, lut: lookup):
     70         copy = self._obj.copy()
---> 71         _cpp.buckets.scale(copy, _cpp.reciprocal(lut.func), lut.dim)
     72         return copy
     73 

VariancesError: Output has no variance but at least one input does.
```

I encountered this when normalising to a monitor. It works when both or none operands have variances.

I don't really understand why this happens, the exception comes from an in-place transform, but I am not using in-place operations here. So conceptually it should work, I think.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Fixes #2400.

### CODE REVIEW

**Review by jl-wynen — COMMENTED** [review]
This fixes the problem. But it does not work when the RHS has variances but the LHS does not. I'm unsure if this is relevant in practice. How difficult would it be make that work?

**Comment by SimonHeybrock** [comment]
> This fixes the problem. But it does not work when the RHS has variances but the LHS does not. I'm unsure if this is relevant in practice. How difficult would it be make that work?

I'd say this is an unrelated limitation. There are two ways to implement this:
- Add variances beforehand (after the call to `copy`), then proceed with current in-place code.
- Add a non-in-place version of `scale`, then you get this for free.

**Comment by jl-wynen** [comment]
Ok. Should we do it now or wait until it is needed?

**Comment by SimonHeybrock** [comment]
Either is fine for me, but independent of this PR, I'd say.

This would also provide a performance optimization, so it would be interesting to implement a benchmark for it (unless we have one already, check https://scipp.github.io/scipp-benchmarks/).

**Review by jl-wynen — APPROVED** [review]

**Pull request merged**
