### PR TITLE
Prepare 0.12.1

### PR DESCRIPTION
**Pull request by nvaytet**
Cherry picking CI fixes and plotting fix for 0.12.1

Do not merge, this is to test if CI works.

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
Is `main` the correct base branch? This means you would, e.g., drop Python 3.7 support in the patch release.

**Comment by nvaytet** [comment]
> Is `main` the correct base branch? This means you would, e.g., drop Python 3.7 support in the patch release.

This is not meant to be merged, my goal was to make a patch release from this branch without merging it, because we didn't want to drop python 3.7 support in 0.12.1.
So I started from 0.12.0, and cherry picked the changes I wanted (including the plotting fix, which is needed to make `ess` work with scipp 0.12).

But maybe there is a better way of doing this?
Wojciech (and the SANS people) would like to use the latest scipp and scippneutron for a detector test this week.

**Comment by SimonHeybrock** [comment]
Even if it does not get merged, you should base the PR on 0.12.0?

**Comment by SimonHeybrock** [comment]
Hmm, maybe you are right, we can just release and merge into `main` after the release?

**Comment by SimonHeybrock** [comment]
In the past I usually made a `release` branch for the purpose of patch releastes, and then kept merging `release` into `main`.

**Comment by SimonHeybrock** [comment]
Can we merge this now that the release is out?

**Pull request closed without merging**
