### PR TITLE
Use American English spelling

### PR DESCRIPTION
**Pull request by jl-wynen**
Covers
- centre
- colour
- favour
- behaviour
- -ise

Anything missing?

### CODE REVIEW

**Comment by OwenArnold** [comment]
Other words to grep for

Organise
Analyse
License

**Comment by SimonHeybrock** [comment]
Please don't merge before #1823 to avoid conflicts.

**Comment by jl-wynen** [comment]
> Organise
> Analyse
> License

Only occur with American spelling (except for span which uses British).

> Please don't merge before #1823 to avoid conflicts.

I don't see any conflicts because I only touched comments in C++, but no problem.

**Review by OwenArnold — APPROVED** [review]
Changes made look good.

**Comment by SimonHeybrock** [comment]
@jl-wynen There is a merge conflict now.

**Comment by jl-wynen** [comment]
Fixed the conflict

**Pull request merged**
