### PR TITLE
Faster 2d image plot

### PR DESCRIPTION
**Pull request by nvaytet**
These changes make the generation and interaction of large 2D images much faster.
It it displaying the data as a background image, instead of drawing 1 square per pixel on the web canvas.
Some tricks are involved to get the `plotly` auto-scale features to work properly.

Displaying a 2000x1000 image:
```Python
N = 2000
M = 1000
xx = np.arange(N, dtype=np.float64)
yy = np.arange(M, dtype=np.float64)
x, y = np.meshgrid(xx, yy)
b = N/1000.0
c = M/100.0
r = np.sqrt(((x-c)/b)**2 + ((y-c)/b)**2)
a = np.sin(r)
d1 = sc.Dataset()
d1.coords[Dim.X] = sc.Variable([Dim.X], values=xx, unit=sc.units.m)
d1.coords[Dim.Y] = sc.Variable([Dim.Y], values=yy, unit=sc.units.m)
d1['Signal'] = sc.Variable([Dim.Y, Dim.X], values=a, unit=sc.units.counts)
```
No rasterization: ~18s render time
```Python
sc.plot(d1, rasterize=False)
```
With rasterization: ~2s render time
```Python
sc.plot(d1, rasterize=True)
```

By default, `rasterize='auto'`, meaning if the image has more than 100,000 pixels, it will switch to rasterize automatically.
Screenshot at 2019-10-11 14-26-02

**Additional fixes:**
- Hide sliders if there are only 2 dimensions
- Correct colormap for 3d projection

### CODE REVIEW

**Comment by nvaytet** [comment]
Yes i was thinking exactly the same thing. That this file is rapidly becoming difficult to maintain. Among other things, I was thinking of maybe turning `scipp-plot` into its own repository, and then split the different functions into different files, and try to reduce the amount of duplicated code.
`scipp` could then either clone or `conda` install `scipp-plot` as a dependency.

Maybe for now another solution is to make a `plot` directory and have many plotting files in there. I don't know if that would help the maintainability.

Finally, as you said, maybe we also need to re-think the whole approach to the plotting. Do we want to slowly move away from a single `plot` function?

**Comment by nvaytet** [comment]
But then if you have the plotting in a separate repo, I am not sure how you can make sure, with the tests, how new changes in `scipp` don't break the plotting. You could run plotting tests in `scipp` but then if they fail, you have no way of updating the plotting as part of the same PR. You would have to update `scipp-plot` for some new changes that are not yet in the `scipp` `master`... doesn't sound right.

**Comment by DanNixon** [comment]
@nvaytet You also need to add Pillow to the Conda dependencies.
As it is now plotting may be broken there.

**Comment by nvaytet** [comment]
Ah right, ok i'll add it. Maybe it would be nice to have a system where we don't need to add dependencies in 2 different places?

**Comment by DanNixon** [comment]
Yes, I have an idea of how it can be done but it will mean changing a lot of our CI.

https://github.com/scipp/scipp/issues/611

**Comment by SimonHeybrock** [comment]
I'd keep it in the same repo, but making a `scipp.plot` submodule may be a good idea.

**Pull request merged**
