### PR TITLE
Fix 1d y axis limits issues

### PR DESCRIPTION
**Pull request by nvaytet**
This fixes:
- the elongated shape of the profile figure (which was due to a `tight_layout()` command which did not factor in the padding
- the profile plot once again automatically rescales after a click to save a plot 
- the warning from a negative log limit when viewing 1d data with `norm="log"` where data was close to zero
- removes the unwanted padding when manually setting `vmin` or `vmax`

### CODE REVIEW

**Comment by nvaytet** [comment]
@arm61 I can't add you as a reviewer (for some reason), but maybe you can take a quick look to see if this fixes some of your issues?

**Comment by arm61** [comment]
From reading the Python (I can't test right now cause I don't have a development `scipp` on my laptop) it looks like it should work. I will try and test tomorrow.

**Comment by arm61** [comment]
Looks like it works for an example (Fresnel decay) reflectometry (large dynamic range) dataset. 

Screenshot 2021-04-23 at 08 55 01

**Review by SimonHeybrock — APPROVED** [review]
Code looks good and changes work for me.

**Pull request merged**
