### PR TITLE
Change licence from GPLv3 to BSD-3

### PR DESCRIPTION
**Pull request by SimonHeybrock**
As discussed, this would change scipp's licence from GPLv3 to BSD-3. The reason for this it to be more in-line with other (Python) projects and allow more outside use/contributions.

**Please indicate your agreement to this licence change by approving this pull-request**

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
@dtasev @arm61 @TC5027 I cannot request a review from you, could you please indicate your agreement by upvoting or commenting. Thanks!

**Review by matthew-d-jones — APPROVED** [review]

**Review by OwenArnold — APPROVED** [review]

**Review by jl-wynen — APPROVED** [review]

**Review by nvaytet — APPROVED** [review]

**Review by dtasev — APPROVED** [review]

**Review by Matthew-Andrew — APPROVED** [review]

**Review by igudich — APPROVED** [review]
Good luck!

**Review by DavidFair — APPROVED** [review]

**Comment by nvaytet** [comment]
Not sure you remembered to also change the license in the conda `meta.yml` file https://github.com/scipp/scipp/blob/main/conda/meta.yaml#L50
Couldn't find it in the diff

**Comment by SimonHeybrock** [comment]
Involved facilities have expressed their approval (in other channels), will merge once builds are green.

**Pull request merged**
