### PR TITLE
Update release notes

### PR DESCRIPTION
**Pull request by SimonHeybrock**

### CODE REVIEW

**Review by jl-wynen — COMMENTED** [review]
I thought we stopped using those?

**Comment by SimonHeybrock** [comment]
Did we? When? In other projects yes, but not Scipp so far?

**Comment by jl-wynen** [comment]
I thought we'd do the same everywhere.

**Review by jl-wynen — APPROVED** [review]

**Comment by SimonHeybrock** [comment]
> I thought we'd do the same everywhere.

We will, but we, e.g., do not have a link in the docs yet.

**Pull request merged**
