### PR TITLE
Add Conda builds to CI

### PR DESCRIPTION
**Pull request by DanNixon**

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
I just added the conda package to the RTD build. Is it possible to delay the RTD CI until the conda CI build has completed? But maybe that is not what we want... not every doc update should trigger a rebuild of the conda package?

**Comment by DanNixon** [comment]
> I just added the conda package to the RTD build.

Not sure what you mean. Is there a separate docs build? I couldn't see this in the Travis config.

We could easily apply some rules that limit what jobs are performed by the CI (e.g. if only `/docs` was touched there is no need to run any builds or tests).

Also note that the Conda build and publish will only run on `master` in any case (it could run on PR builds too, but there is limited need for it to).

**Comment by SimonHeybrock** [comment]
It is not done by Travis, it is a separate hook for RTD.

**Comment by SimonHeybrock** [comment]
"Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code." ... should work once merged.

**Pull request merged**
