### PR TITLE
Fix error in new plotting when zooming in and returning to 'Home' with datetime axis

### LINKED ISSUE #2672: [experimental plotting] Error raised when zooming and clicking Home with datetime64 axis

### PR DESCRIPTION
**Pull request by nvaytet**
Simple example:
```Py
import numpy as np
import scipp as sc
%matplotlib widget

sc.plotting.select_backend('experimental')

time = sc.array(dims=['time'], values=np.arange(np.datetime64('1907-11-20T23:58:17'),
                                                np.datetime64('2017-03-01T00:05:17'), 1000000))
data = sc.DataArray(data=sc.array(dims=['time'], values=np.random.rand(time.sizes['time'])),
                    coords={'time':time})
data.plot()
```

Then zoom, and then click 'Home'.

Fixes #2672

### CODE REVIEW

**Comment by nvaytet** [comment]
@SimonHeybrock did you have any more comments on this?

**Comment by nvaytet** [comment]
I think I misunderstood the question a little and answered off-topic.

Basically, the delta is used to compute padding around the first and last data point.
I don't expect the rounding down to really matter, because we would always be using this delta to extend the range beyond `coord.min()` and `coord.max()`. You are correct that that the padding could potentially be 0 in some edge cases, but you would still not miss the last point, as the limits will be set to exactly `min()` and `max()`.

Unless you know a good way to add a floating point number of e.g. seconds to a datetime?

**Comment by SimonHeybrock** [comment]
Maybe a stupid question: Why do we need to do this at all? Isn't Matplotlib doing this on its own? If it is not, why is there (as the title implies) different logic between initial plot and pressing the home button? Can't we just save the original limits in that case?

**Comment by nvaytet** [comment]
> Why do we need to do this at all? Isn't Matplotlib doing this on its own? 

I was thinking the same when I started working on that PR, and in principle this was the goal. To let the library do as much work as we can get it to do.

Initially, this was in place for multiple reasons.
1. The log scaling by matplotlib would go wrong when negative values were present in the data
2. I was making an image with a default extent and then updating it when receiving the actual data, but matplotlib wouldn't update the limits so I had to do this manually
3. Log scaling doesn't work very well on 2d images (see screenshots below)

It seems now that 1. no longer applies with the current version of mpl i have installed (3.4), that 2. no longer occurs because I am now using pcolormesh instead of imshow, but 3. still applies:

without custom limits
Screenshot at 2022-07-18 09-17-19

with custom limits
Screenshot at 2022-07-18 09-18-37

**Comment by nvaytet** [comment]
no, it's as soon as you switch to `log` scale (and you would get the same if you could set the log scale with a keyword arg).

**Review by SimonHeybrock — APPROVED** [review]

**Pull request merged**
