### PR TITLE
nbsphinx error prevent documentation build

### PR DESCRIPTION
**Pull request by OwenArnold**
Fix generated from python code applied to notebooks in docs/:

```python
import nbformat as nbf 
from glob import glob

# Collect a list of all notebooks in the content folder
notebooks = glob("./**/*.ipynb", recursive=True)

for ipath in notebooks:
    ntbk = nbf.read(ipath, as_version=nbf.NO_CONVERT)
    ntbk.metadata['widgets'] = ''
    for cell in ntbk.cells:
        if cell.get('cell_type') == 'markdown':
            cell_tags = cell.get('metadata', {})['tags'] = []
   
    nbf.write(ntbk, ipath)

```

### CODE REVIEW

**Comment by OwenArnold** [comment]
We may no longer need this. conda env seems to have rectified itself since yesterday. https://dev.azure.com/scipp/scipp/_build/results?buildId=5101&view=logs&j=2f8f8533-8a07-571e-ae6b-6524514847e1

**Comment by OwenArnold** [comment]
I now think that the problem was not with nbsphinx directly, but due to an update in an unpinned dependent library `jinja` which was released under v3 and seems to have introduced some parsing errors. Note [this](https://github.com/spatialaudio/nbsphinx/commit/5f702d21db41a0ee5691540555b0085e5d6fdab5#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L18) and [this](https://github.com/pallets/jinja/issues/1427)

**Comment by SimonHeybrock** [comment]
Does this mean we have to pin to a previous version?

**Comment by OwenArnold** [comment]
> Does this mean we have to pin to a previous version?

No we can continue using 0.8.5 as the bad package files have since been replaced directly.

**Pull request closed without merging**
