### PR TITLE
Preparations for release 0.11

### PR DESCRIPTION
**Pull request by SimonHeybrock**

### CODE REVIEW

**Review by jl-wynen — APPROVED** [review]
Looks good.

Do we want to include https://github.com/scipp/scipp/issues/2371? The only thing missing there is the comparison with numpy that I mentioned in the last comment.

**Comment by SimonHeybrock** [comment]
> Looks good.
> 
> Do we want to include #2371? The only thing missing there is the comparison with numpy that I mentioned in the last comment.

I think we can do without that comparison for now? If you open a PR we can include it (can you refactor `to` while you are at it?).

**Comment by jl-wynen** [comment]
Why refactor `to`?

**Comment by SimonHeybrock** [comment]
> Why refactor `to`?

It had to use some messy code for dtype comparisons, which is why I noticed our `dtype` shortcomings in the first place.

**Pull request merged**
