### PR TITLE
Use conda forge pinning attempt 2

### LINKED ISSUE #257: Print configuration error at the end of CMake output if external dependencies fail to install
Currently, if I don't have `mercurial` installed, when trying to clone `Eigen`, I get the following error in the middle of the `CMake` output:
```
CMake Error at /usr/share/cmake-3.10/Modules/ExternalProject.cmake:2335 (message):
  error: could not find hg for clone of Eigen
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/ExternalProject.cmake:3029 (_ep_add_download_command)
  CMakeLists.txt:6 (ExternalProject_Add)

-- Configuring incomplete, errors occurred!
See also "/home/nvaytet/work/code/scipp/source/build/Eigen-download/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
```
However, I only see this if I scroll back up and carefully go through the output.
The end of the `CMake` output looks like
```
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Found Threads: TRUE  
-- Boost version: 1.69.0
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nvaytet/work/code/scipp/source/build
```
which leads me to believe that everything went well during the configuration process.
I think it would be useful to have a global message at the end to confirm that everything went ok or that there were some errors.

### PR DESCRIPTION
**Pull request by jl-wynen**
Fixes #257

### CODE REVIEW

**Comment by jl-wynen** [comment]
Seems to work now. I used a separate workflow to test it: https://github.com/scipp/scipp/actions/workflows/test-release.yml
Should I run the actual release workflow, too? Or is this a waste of computer time?

**Comment by SimonHeybrock** [comment]
> Seems to work now. I used a separate workflow to test it: https://github.com/scipp/scipp/actions/workflows/test-release.yml Should I run the actual release workflow, too? Or is this a waste of computer time?

Maybe disable parts of the matrix temporarily, and also the wheel builds? Or cancel jobs by hand after you start it.

**Comment by jl-wynen** [comment]
The release pipeline passed: https://github.com/scipp/scipp/actions/runs/4052037620

It used the pinned compilers from conda-forge according to the logs. The Ubuntu py3.8 package has this `index.json`:
```json
{
  "arch": "x86_64",
  "build": "py38hfbd4bf9_16",
  "build_number": 16,
  "depends": [
    "confuse",
    "graphlib-backport",
    "libgcc-ng >=12",
    "libstdcxx-ng >=12",
    "numpy",
    "python >=3.8,<3.9.0a0",
    "python_abi 3.8.* *_cp38",
    "pyyaml",
    "tbb 2020.2.*"
  ],
  "license": "BSD-3-Clause",
  "name": "scipp",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1675154938521,
  "version": "23.01.1"
}
```

So it depends on the correct version of Python.

But the libgcc version is 12 even though it was built with 11, the log shows
```
libgcc-devel_linux-64:    11.3.0-h210ce93_19
libgcc-ng:                12.2.0-h65d4601_19
```
I don't know if this is an issue.

The numpy version is not pinned. And has no lower limit. The logs show that conda used 1.24 in the test env. This seems to contradict the pinned 1.20. But I don't know if pins affect the test env.

Comparing with the latest actual release, the numpy and Python versions are the same.
The libgcc version in the package dependencies is `11.1.0`. But the build logs show that conda used 12 even in the last release.

**Comment by jl-wynen** [comment]
@SimonHeybrock Are you happy with this? If so, I am going to revert the last commit and let the regular PR workflow run.

**Comment by SimonHeybrock** [comment]
Will this work on a system without gcc 12 then?

**Comment by jl-wynen** [comment]
It depends on the standard library so it should install it from conda. We don't want to link against the system library anyway.

**Comment by jl-wynen** [comment]
But since installing from the package file doesn't install dependencies, I don't see another way to test this other than try it and see if the next release works.

**Pull request merged**
