### PR TITLE
More flexibility in scipp ci

### PR DESCRIPTION
**Pull request by OwenArnold**
We have historically needed long-running development branches (similar to `main`) to accommodate major changes, such as the recent `dev` branch for shallow copies.

This small changes demonstrates that we can utilise much of the existing infrastructure for this with a small change to prevent publication of latest documentation.

1. We can use full ci to do full integration testing on accumulated changes on the branch across all platforms (and docs), not just PR by PR. We can also merge in changes from `main` and check those if required.
1. Publishing to some other label i.e `next` (as done below) allow us to test and work on downstream projects such as scippneutron ahead of the next upstream release. `next` seems to be a convenient label to use for the channel.

* See example "Next" pipeline. built from `next.yml`
* **Note that the next pipeline and file should be removed before these changes are merged**

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
It is not clear to me why we need this right now? Also, wouldn't it imply we would need **four** pipelines downstream, e.g., in `scippneutron`:
- `scippneutron/Release` using `scipp/label/main`
- `scippneutron/Main` using `scipp/label/main`
- `scippneutron/next` using `scipp/label/dev`
- `scippneutron/next-next` using `scipp/label/next`

**Comment by OwenArnold** [comment]
> It is not clear to me why we need this right now? Also, wouldn't it imply we would need **four** pipelines downstream, e.g., in `scippneutron`:
> 
> * `scippneutron/Release` using `scipp/label/main`
> * `scippneutron/Main` using `scipp/label/main`
> * `scippneutron/next` using `scipp/label/dev`
> * `scippneutron/next-next` using `scipp/label/next`

Yes, that would be the correct chain for the downstream projects. Alternatively (as we have done) only address downstream projects at the point that `scipp/label/dev` contains the changes you need.

We don't need this right now, but since we are hoping to get a nicely working set of pipeline configurations that we can apply to our downstream projects, it might be timely to add this before it's further duplicated.

**Comment by SimonHeybrock** [comment]
Is this still relevant, or can it be closed?

**Comment by OwenArnold** [comment]
Closing, but i think some of the changes are still relevant for working on `next` branches for the pipelines git repo. Those can be reimplemented if we need them.

**Pull request closed without merging**
