### PR TITLE
Disable sliders when dim has length 1

### LINKED ISSUE #1523: Disable sliders with single bin in Slice View
Noted while looking through https://scipp.github.io/tutorials/neutron-diffraction.html Single TOF bin, but appears to have the ability to set thickness and slice position.

image (2)

Discussed with Neil that we should disable the slice and thickness control for a single TOF value. Otherwise looks like broken functionality. Maybe additionally provide a tool-tip explanation.

### PR DESCRIPTION
**Pull request by nvaytet**
Fixes #1523

### CODE REVIEW

**Review by OwenArnold — CHANGES_REQUESTED** [review]
Other controls need to be disabled too. Such as continuous update check box.
image

**Comment by nvaytet** [comment]
Are there any other controls apart from the continuous_update checkbox that I forgot?

**Comment by nvaytet** [comment]
I don't really know where to add the tooltip.
Tooltip support in ipywidgets is not great. Only buttons and togglebuttons have proper tooltips (see https://github.com/jupyter-widgets/ipywidgets/issues/421)
For other widgets, they seem to be linked to the description, which would require modifying and then (sometimes partially) hiding the description of the disabled widgets.
I suggest we leave the tooltip out for now, I think it's kind of obvious why it's disabled, especially when you have multiple dimensions and sliders get re-enabled once you swap the axes.

**Comment by OwenArnold** [comment]
> I suggest we leave the tooltip out for now, I think it's kind of obvious why it's disabled, especially when you have multiple dimensions and sliders get re-enabled once you swap the axes
👍

**Review by OwenArnold — APPROVED** [review]
Works as advertised. After applying `sc.bin` we get slice behaviour back.

**Pull request merged**
