### PR TITLE
Add concept documentation for upcoming coord handling

### PR DESCRIPTION
**Pull request by SimonHeybrock**
This is an attempt to write down all concepts/contracts that data arrays and datasets have to fulfil, related to slicing, coord, and aligned/unaligned mechanism. Probably quite a few missing, can you help to complete the list? Please comment!

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
> Looks good. Examples work for me.

That is not what I wanted to hear. :)
We need to try and poke hole into this to find any remaining subtleties and loopholes.

**Comment by OwenArnold** [comment]
> > Looks good. Examples work for me.
> 
> That is not what I wanted to hear. :)
> We need to try and poke hole into this to find any remaining subtleties and loopholes.

Fair point. I'll try a little harder to break things.

**Comment by SimonHeybrock** [comment]
Specifically, I would like to develop this into a *complete* contract of data array and dataset, i.e., we should use this to fully specify the behavior. One thing I definitely will need to add is the bevahior with 2D coordinates.

**Comment by nvaytet** [comment]
I'll add comments one at a time, as they come to mind, instead of delaying until I feel I've done a thorough review.

Do we also want to describe the behaviour we expect when using `del`, as described in https://github.com/scipp/scipp/issues/1176 ?

**Comment by nvaytet** [comment]
I'm not sure if here you want to limit yourself to the slicing and coord handling, since you mention 

> Specifically, I would like to develop this into a _complete_ contract of data array and dataset, i.e., we should use this to fully specify the behavior. One thing I definitely will need to add is the bevahior with 2D coordinates.

but unrelated to slicing, I guess we can also describe the behaviour of inserting coordinates, e.g. we allow to add data before coordinates. We can add bin-centered coordinates, or bin-edges
Screenshot_2020-06-30_10-10-51

**Comment by SimonHeybrock** [comment]
See also results from a wider discussion of related issues and concepts: https://github.com/scipp/scipp/issues/1155#issuecomment-652439963.

**Comment by SimonHeybrock** [comment]
While not complete as discussed, I will merge this so it can be updated and used for testing in the coord refactor I am working on. Since it is only in the dev docs there is little risk of confusion for users at this point.

**Pull request merged**
