### PR TITLE
Enable Python-3.10 conda builds after blocking conan update

### PR DESCRIPTION
**Pull request by SimonHeybrock**

### CODE REVIEW

**Review by jl-wynen — APPROVED** [review]
:+1: provided that the release workflow passes.

**Comment by SimonHeybrock** [comment]
Obviously this does not work, because the problem is the conda build, i.e., the conan update in the pip bits are irrelevant.

**Comment by jl-wynen** [comment]
I don't understand, you set the version for the conda build stage?

**Comment by SimonHeybrock** [comment]
The conda conan is still too old apparently.

**Pull request closed without merging**
